import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Next-Auth
import MySessionProvider from "@/components/common/user/Provider";

// Global Styles, useSession()
import GlobalSetting from "@/components/common/GlobalSetting";
import Navigation from "./ui/Navigation";

const inter = Inter({ subsets: ["latin"] });

// 직접 넣으면 안되고 Metadata api를 이용해서 넣어야 한다.
export const metadata: Metadata = {
  title: "🦋Lovable Passages🦋",
  description: "Generated by jjhh",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <MySessionProvider>
          <GlobalSetting>
            <Navigation />
            {children}
          </GlobalSetting>
        </MySessionProvider>
      </body>
    </html>
  );
}
