import HomePage from "./home-page";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import UserSetting from "@/components/common/user";

const inter = Inter({ subsets: ["latin"] });

// 직접 넣으면 안되고 Metadata api를 이용해서 넣어야 한다.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
